apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: rails-app
      docker:
        dockerfile: Dockerfile
  local:
    push: false

deploy:
  helm:
    releases:
      - name: postgres
        chartPath: charts/postgres
        valuesFiles:
          - charts/postgres/values.yaml
        namespace: default
        createNamespace: true
      - name: redis
        chartPath: charts/redis
        valuesFiles:
          - charts/redis/values.yaml
        namespace: default
        createNamespace: true
      - name: rails-app
        chartPath: charts/rails-app
        valuesFiles:
          - charts/rails-app/values.yaml
        namespace: default
        createNamespace: true
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_rails_app}}"
          image.tag: "{{.IMAGE_TAG_rails_app}}"

portForward:
  - resourceType: service
    resourceName: postgres
    namespace: default
    port: 5432
    localPort: 5432
  - resourceType: service
    resourceName: redis
    namespace: default
    port: 6379
    localPort: 6379
  - resourceType: service
    resourceName: rails-app
    namespace: default
    port: 3000
    localPort: 3000
