apiVersion: skaffold/v4beta11
kind: Config
deploy:
  helm:
    releases:
      - name: postgres
        chartPath: charts/postgres
        valuesFiles:
          - charts/postgres/values.yaml
        namespace: default
        createNamespace: true
      - name: redis
        chartPath: charts/redis
        valuesFiles:
          - charts/redis/values.yaml
        namespace: default
        createNamespace: true

portForward:
  - resourceType: service
    resourceName: postgres
    namespace: default
    port: 5432
    localPort: 5432
  - resourceType: service
    resourceName: redis
    namespace: default
    port: 6379
    localPort: 6379
