apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "redis.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["redis-server", "--appendonly", "yes", "--dir", "/data"]
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
      {{- if not .Values.storage.pvc.enabled }}
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.storage.hostPath }}
            type: DirectoryOrCreate
      {{- end }}
  {{- if .Values.storage.pvc.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.storage.pvc.storageClass }}
        storageClassName: {{ .Values.storage.pvc.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.pvc.size }}
  {{- end }}
